#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

LABEL @BOOTMGR_ANDROID_DISTRIBUTION_NAME@ - Mount userdata from images
    KERNEL /@BOOTMGR_ANDROID_DIR_NAME@/kernel
    INITRD /@BOOTMGR_ANDROID_DIR_NAME@/ramdisk-all-combined.img
    APPEND @STRIPPED_BOARD_KERNEL_CMDLINE@ androidboot.android_dir=@BOOTMGR_ANDROID_DIR_NAME@  androidboot.mount_system=imgs androidboot.mount_userdata=imgs

LABEL @BOOTMGR_ANDROID_DISTRIBUTION_NAME@ - Mount userdata from subdirs
    KERNEL /@BOOTMGR_ANDROID_DIR_NAME@/kernel
    INITRD /@BOOTMGR_ANDROID_DIR_NAME@/ramdisk-all-combined.img
    APPEND @STRIPPED_BOARD_KERNEL_CMDLINE@ androidboot.android_dir=@BOOTMGR_ANDROID_DIR_NAME@  androidboot.mount_system=imgs androidboot.mount_userdata=bind_mount_dir

LABEL @BOOTMGR_ANDROID_DISTRIBUTION_NAME@ - Store userdata in RAM
    KERNEL /@BOOTMGR_ANDROID_DIR_NAME@/kernel
    INITRD /@BOOTMGR_ANDROID_DIR_NAME@/ramdisk-all-combined.img
    APPEND @STRIPPED_BOARD_KERNEL_CMDLINE@ androidboot.android_dir=@BOOTMGR_ANDROID_DIR_NAME@  androidboot.mount_system=imgs androidboot.mount_userdata=tmpfs

LABEL @BOOTMGR_ANDROID_DISTRIBUTION_NAME@ - Store system and userdata in RAM
    KERNEL /@BOOTMGR_ANDROID_DIR_NAME@/kernel
    INITRD /@BOOTMGR_ANDROID_DIR_NAME@/ramdisk-all-combined.img
    APPEND @STRIPPED_BOARD_KERNEL_CMDLINE@ androidboot.android_dir=@BOOTMGR_ANDROID_DIR_NAME@  androidboot.mount_system=imgs_ram androidboot.mount_userdata=tmpfs
