#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

menuentry "@BOOTMGR_ANDROID_DISTRIBUTION_NAME@" {
    ostype Linux
    loader \@BOOTMGR_ANDROID_DIR_NAME@\kernel
    initrd \@BOOTMGR_ANDROID_DIR_NAME@\ramdisk.img
    options "@STRIPPED_BOARD_KERNEL_CMDLINE@ androidboot.android_dir=@BOOTMGR_ANDROID_DIR_NAME@"
    submenuentry "Mount userdata from images" {
        add_options "androidboot.mount_system=imgs androidboot.mount_userdata=imgs"
    }
    submenuentry "Mount userdata from subdirs" {
        add_options "androidboot.mount_system=imgs androidboot.mount_userdata=bind_mount_dir"
    }
    submenuentry "Store userdata in RAM" {
        add_options "androidboot.mount_system=imgs androidboot.mount_userdata=tmpfs"
    }
    submenuentry "Store system and userdata in RAM" {
        add_options "androidboot.mount_system=imgs_ram androidboot.mount_userdata=tmpfs"
    }
}
